/*
 * generated by Xtext
 */
parser grammar InternalFragmentTestLanguageExParser;

options {
	tokenVocab=InternalFragmentTestLanguageExLexer;
	superClass=AbstractInternalAntlrParser;
	
}

@header {
package org.eclipse.xtext.parser.fragments.parser.antlr.internal; 

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.eclipse.xtext.parser.fragments.services.FragmentTestLanguageExGrammarAccess;

}

@members {


	private FragmentTestLanguageExGrammarAccess grammarAccess;
	 	
	public InternalFragmentTestLanguageExParser(TokenStream input, FragmentTestLanguageExGrammarAccess grammarAccess) {
		this(input);
		this.grammarAccess = grammarAccess;
		registerRules(grammarAccess.getGrammar());
	}
	
	@Override
	protected String getFirstRuleName() {
		return "ParserRuleFragmentsEx";	
	} 
	   	   	
	@Override
	protected FragmentTestLanguageExGrammarAccess getGrammarAccess() {
		return grammarAccess;
	}
}

@rulecatch { 
	catch (RecognitionException re) { 
	    recover(input,re); 
	    appendSkippedTokens();
	}
}




// Entry rule entryRuleParserRuleFragmentsEx
entryRuleParserRuleFragmentsEx returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getParserRuleFragmentsExRule()); }
	 iv_ruleParserRuleFragmentsEx=ruleParserRuleFragmentsEx 
	 { $current=$iv_ruleParserRuleFragmentsEx.current; } 
	 EOF 
;

// Rule ParserRuleFragmentsEx
ruleParserRuleFragmentsEx returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:

    { 
        newCompositeNode(grammarAccess.getParserRuleFragmentsExAccess().getParserRuleFragmentsParserRuleCall()); 
    }
    this_ParserRuleFragments_0=ruleParserRuleFragments
    {
        $current = $this_ParserRuleFragments_0.current;
        afterParserOrEnumRuleCall();
    }

;





// Entry rule entryRuleParserRuleFragments
entryRuleParserRuleFragments returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getParserRuleFragmentsRule()); }
	 iv_ruleParserRuleFragments=ruleParserRuleFragments 
	 { $current=$iv_ruleParserRuleFragments.current; } 
	 EOF 
;

// Rule ParserRuleFragments
ruleParserRuleFragments returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((
    {
        $current = forceCreateModelElement(
            grammarAccess.getParserRuleFragmentsAccess().getParserRuleFragmentsAction_0(),
            $current);
    }
)((
	otherlv_1=NumberSignDigitOne
    {
    	newLeafNode(otherlv_1, grammarAccess.getParserRuleFragmentsAccess().getNumberSignDigitOneKeyword_1_0_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getParserRuleFragmentsAccess().getElementPRFNamedParserRuleCall_1_0_1_0()); 
	    }
		lv_element_2_0=rulePRFNamed		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getParserRuleFragmentsRule());
	        }
       		set(
       			$current, 
       			"element",
        		lv_element_2_0, 
        		"PRFNamed");
	        afterParserOrEnumRuleCall();
	    }

)
))
    |(
	otherlv_3=NumberSignDigitTwo
    {
    	newLeafNode(otherlv_3, grammarAccess.getParserRuleFragmentsAccess().getNumberSignDigitTwoKeyword_1_1_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getParserRuleFragmentsAccess().getElementPRFNamedParserRuleCall_1_1_1_0()); 
	    }
		lv_element_4_0=rulePRFNamed		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getParserRuleFragmentsRule());
	        }
       		set(
       			$current, 
       			"element",
        		lv_element_4_0, 
        		"PRFNamed");
	        afterParserOrEnumRuleCall();
	    }

)
)
	otherlv_5=HyphenMinusGreaterThanSign
    {
    	newLeafNode(otherlv_5, grammarAccess.getParserRuleFragmentsAccess().getHyphenMinusGreaterThanSignKeyword_1_1_2());
    }
(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getParserRuleFragmentsRule());
	        }
        }
	otherlv_6=RULE_ID
	{
		newLeafNode(otherlv_6, grammarAccess.getParserRuleFragmentsAccess().getRefPRFNamedCrossReference_1_1_3_0()); 
	}

)
))
    |(
	otherlv_7=NumberSignDigitThree
    {
    	newLeafNode(otherlv_7, grammarAccess.getParserRuleFragmentsAccess().getNumberSignDigitThreeKeyword_1_2_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getParserRuleFragmentsAccess().getElementPRFNamedRefFirstParserRuleCall_1_2_1_0()); 
	    }
		lv_element_8_0=rulePRFNamedRefFirst		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getParserRuleFragmentsRule());
	        }
       		set(
       			$current, 
       			"element",
        		lv_element_8_0, 
        		"PRFNamedRefFirst");
	        afterParserOrEnumRuleCall();
	    }

)
))
    |(
	otherlv_9=NumberSignDigitFour
    {
    	newLeafNode(otherlv_9, grammarAccess.getParserRuleFragmentsAccess().getNumberSignDigitFourKeyword_1_3_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getParserRuleFragmentsAccess().getElementPRFNamedWithActionParserRuleCall_1_3_1_0()); 
	    }
		lv_element_10_0=rulePRFNamedWithAction		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getParserRuleFragmentsRule());
	        }
       		set(
       			$current, 
       			"element",
        		lv_element_10_0, 
        		"PRFNamedWithAction");
	        afterParserOrEnumRuleCall();
	    }

)
))
    |(
	otherlv_11=NumberSignDigitFive
    {
    	newLeafNode(otherlv_11, grammarAccess.getParserRuleFragmentsAccess().getNumberSignDigitFiveKeyword_1_4_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getParserRuleFragmentsAccess().getElementPRFNamedWithActionInFragmentParserRuleCall_1_4_1_0()); 
	    }
		lv_element_12_0=rulePRFNamedWithActionInFragment		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getParserRuleFragmentsRule());
	        }
       		set(
       			$current, 
       			"element",
        		lv_element_12_0, 
        		"PRFNamedWithActionInFragment");
	        afterParserOrEnumRuleCall();
	    }

)
))
    |(
	otherlv_13=NumberSignDigitSix
    {
    	newLeafNode(otherlv_13, grammarAccess.getParserRuleFragmentsAccess().getNumberSignDigitSixKeyword_1_5_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getParserRuleFragmentsAccess().getElementPRFNamedWithActionInFragment2ParserRuleCall_1_5_1_0()); 
	    }
		lv_element_14_0=rulePRFNamedWithActionInFragment2		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getParserRuleFragmentsRule());
	        }
       		set(
       			$current, 
       			"element",
        		lv_element_14_0, 
        		"PRFNamedWithActionInFragment2");
	        afterParserOrEnumRuleCall();
	    }

)
))
    |(
	otherlv_15=NumberSignDigitSeven
    {
    	newLeafNode(otherlv_15, grammarAccess.getParserRuleFragmentsAccess().getNumberSignDigitSevenKeyword_1_6_0());
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getParserRuleFragmentsAccess().getElementPRFNamedWithActionInFragment3ParserRuleCall_1_6_1_0()); 
	    }
		lv_element_16_0=rulePRFNamedWithActionInFragment3		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getParserRuleFragmentsRule());
	        }
       		set(
       			$current, 
       			"element",
        		lv_element_16_0, 
        		"PRFNamedWithActionInFragment3");
	        afterParserOrEnumRuleCall();
	    }

)
))))
;





// Entry rule entryRulePRFNamed
entryRulePRFNamed returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getPRFNamedRule()); }
	 iv_rulePRFNamed=rulePRFNamed 
	 { $current=$iv_rulePRFNamed.current; } 
	 EOF 
;

// Rule PRFNamed
rulePRFNamed returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
    { 
        newCompositeNode(grammarAccess.getPRFNamedAccess().getPRFNamedFragmentParserRuleCall_0()); 
    }
    this_PRFNamedFragment_0=rulePRFNamedFragment
    {
        $current = $this_PRFNamedFragment_0.current;
        afterParserOrEnumRuleCall();
    }
((
	otherlv_1=Colon
    {
    	newLeafNode(otherlv_1, grammarAccess.getPRFNamedAccess().getColonKeyword_1_0_0());
    }
(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedRule());
	        }
        }
	otherlv_2=RULE_ID
	{
		newLeafNode(otherlv_2, grammarAccess.getPRFNamedAccess().getRefPRFNamedCrossReference_1_0_1_0()); 
	}

)
))
    |(
	otherlv_3=HyphenMinus
    {
    	newLeafNode(otherlv_3, grammarAccess.getPRFNamedAccess().getHyphenMinusKeyword_1_1_0());
    }

    { 
        newCompositeNode(grammarAccess.getPRFNamedAccess().getPRFNamedRefParserRuleCall_1_1_1()); 
    }
    this_PRFNamedRef_4=rulePRFNamedRef
    {
        $current = $this_PRFNamedRef_4.current;
        afterParserOrEnumRuleCall();
    }
))?)
;





// Entry rule entryRulePRFNamedRefFirst
entryRulePRFNamedRefFirst returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getPRFNamedRefFirstRule()); }
	 iv_rulePRFNamedRefFirst=rulePRFNamedRefFirst 
	 { $current=$iv_rulePRFNamedRefFirst.current; } 
	 EOF 
;

// Rule PRFNamedRefFirst
rulePRFNamedRefFirst returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedRefFirstRule());
	        }
        }
	otherlv_0=RULE_ID
	{
		newLeafNode(otherlv_0, grammarAccess.getPRFNamedRefFirstAccess().getRefPRFNamedCrossReference_0_0()); 
	}

)
)
	otherlv_1=LessThanSignHyphenMinus
    {
    	newLeafNode(otherlv_1, grammarAccess.getPRFNamedRefFirstAccess().getLessThanSignHyphenMinusKeyword_1());
    }

    { 
        newCompositeNode(grammarAccess.getPRFNamedRefFirstAccess().getPRFNamedFragmentParserRuleCall_2()); 
    }
    this_PRFNamedFragment_2=rulePRFNamedFragment
    {
        $current = $this_PRFNamedFragment_2.current;
        afterParserOrEnumRuleCall();
    }
)
;





// Entry rule entryRulePRFNamedWithAction
entryRulePRFNamedWithAction returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getPRFNamedWithActionRule()); }
	 iv_rulePRFNamedWithAction=rulePRFNamedWithAction 
	 { $current=$iv_rulePRFNamedWithAction.current; } 
	 EOF 
;

// Rule PRFNamedWithAction
rulePRFNamedWithAction returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
    { 
        newCompositeNode(grammarAccess.getPRFNamedWithActionAccess().getPRFNamedParserRuleCall_0()); 
    }
    this_PRFNamed_0=rulePRFNamed
    {
        $current = $this_PRFNamed_0.current;
        afterParserOrEnumRuleCall();
    }
(
    {
        $current = forceCreateModelElementAndSet(
            grammarAccess.getPRFNamedWithActionAccess().getPRFNamedWithActionPrevAction_1(),
            $current);
    }
)(
(
		lv_name_2_0=RULE_ID
		{
			newLeafNode(lv_name_2_0, grammarAccess.getPRFNamedWithActionAccess().getNameIDTerminalRuleCall_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedWithActionRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_2_0, 
        		"ID");
	    }

)
)((
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedWithActionRule());
	        }
        }
	otherlv_3=RULE_ID
	{
		newLeafNode(otherlv_3, grammarAccess.getPRFNamedWithActionAccess().getRefPRFNamedCrossReference_3_0_0()); 
	}

)
)(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedWithActionRule());
	        }
        }
	otherlv_4=RULE_ID
	{
		newLeafNode(otherlv_4, grammarAccess.getPRFNamedWithActionAccess().getRef2PRFNamedCrossReference_3_1_0()); 
	}

)
))?)
;





// Entry rule entryRulePRFNamedWithActionInFragment
entryRulePRFNamedWithActionInFragment returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getPRFNamedWithActionInFragmentRule()); }
	 iv_rulePRFNamedWithActionInFragment=rulePRFNamedWithActionInFragment 
	 { $current=$iv_rulePRFNamedWithActionInFragment.current; } 
	 EOF 
;

// Rule PRFNamedWithActionInFragment
rulePRFNamedWithActionInFragment returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
    { 
        newCompositeNode(grammarAccess.getPRFNamedWithActionInFragmentAccess().getFragmentWithActionParserRuleCall_0()); 
    }
    this_FragmentWithAction_0=ruleFragmentWithAction
    {
        $current = $this_FragmentWithAction_0.current;
        afterParserOrEnumRuleCall();
    }
(
	otherlv_1=HyphenMinus
    {
    	newLeafNode(otherlv_1, grammarAccess.getPRFNamedWithActionInFragmentAccess().getHyphenMinusKeyword_1_0());
    }
(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedWithActionInFragmentRule());
	        }
        }
	otherlv_2=RULE_ID
	{
		newLeafNode(otherlv_2, grammarAccess.getPRFNamedWithActionInFragmentAccess().getRefPRFNamedCrossReference_1_1_0()); 
	}

)
))?)
;





// Entry rule entryRulePRFNamedWithActionInFragment2
entryRulePRFNamedWithActionInFragment2 returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getPRFNamedWithActionInFragment2Rule()); }
	 iv_rulePRFNamedWithActionInFragment2=rulePRFNamedWithActionInFragment2 
	 { $current=$iv_rulePRFNamedWithActionInFragment2.current; } 
	 EOF 
;

// Rule PRFNamedWithActionInFragment2
rulePRFNamedWithActionInFragment2 returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((
(
		lv_name_0_0=RULE_ID
		{
			newLeafNode(lv_name_0_0, grammarAccess.getPRFNamedWithActionInFragment2Access().getNameIDTerminalRuleCall_0_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedWithActionInFragment2Rule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_0_0, 
        		"ID");
	    }

)
)
    { 
        newCompositeNode(grammarAccess.getPRFNamedWithActionInFragment2Access().getFragmentWithAction2ParserRuleCall_1()); 
    }
    this_FragmentWithAction2_1=ruleFragmentWithAction2
    {
        $current = $this_FragmentWithAction2_1.current;
        afterParserOrEnumRuleCall();
    }
(
	otherlv_2=HyphenMinus
    {
    	newLeafNode(otherlv_2, grammarAccess.getPRFNamedWithActionInFragment2Access().getHyphenMinusKeyword_2_0());
    }
(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedWithActionInFragment2Rule());
	        }
        }
	otherlv_3=RULE_ID
	{
		newLeafNode(otherlv_3, grammarAccess.getPRFNamedWithActionInFragment2Access().getRefPRFNamedCrossReference_2_1_0()); 
	}

)
))?)
;





// Entry rule entryRulePRFNamedWithActionInFragment3
entryRulePRFNamedWithActionInFragment3 returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getPRFNamedWithActionInFragment3Rule()); }
	 iv_rulePRFNamedWithActionInFragment3=rulePRFNamedWithActionInFragment3 
	 { $current=$iv_rulePRFNamedWithActionInFragment3.current; } 
	 EOF 
;

// Rule PRFNamedWithActionInFragment3
rulePRFNamedWithActionInFragment3 returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
    { 
        newCompositeNode(grammarAccess.getPRFNamedWithActionInFragment3Access().getFragmentWithAction3ParserRuleCall_0()); 
    }
    this_FragmentWithAction3_0=ruleFragmentWithAction3
    {
        $current = $this_FragmentWithAction3_0.current;
        afterParserOrEnumRuleCall();
    }
(
	otherlv_1=HyphenMinus
    {
    	newLeafNode(otherlv_1, grammarAccess.getPRFNamedWithActionInFragment3Access().getHyphenMinusKeyword_1_0());
    }
(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedWithActionInFragment3Rule());
	        }
        }
	otherlv_2=RULE_ID
	{
		newLeafNode(otherlv_2, grammarAccess.getPRFNamedWithActionInFragment3Access().getRefPRFNamedCrossReference_1_1_0()); 
	}

)
))?)
;





// Entry rule entryRuleFragmentWithAction
entryRuleFragmentWithAction returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getFragmentWithActionRule()); }
	 iv_ruleFragmentWithAction=ruleFragmentWithAction 
	 { $current=$iv_ruleFragmentWithAction.current; } 
	 EOF 
;

// Rule FragmentWithAction
ruleFragmentWithAction returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((
(
		lv_name_0_0=RULE_ID
		{
			newLeafNode(lv_name_0_0, grammarAccess.getFragmentWithActionAccess().getNameIDTerminalRuleCall_0_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getFragmentWithActionRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_0_0, 
        		"ID");
	    }

)
)(
    {
        $current = forceCreateModelElementAndSet(
            grammarAccess.getFragmentWithActionAccess().getPRFNamedWithActionPrevAction_1(),
            $current);
    }
)(
(
		lv_name_2_0=RULE_ID
		{
			newLeafNode(lv_name_2_0, grammarAccess.getFragmentWithActionAccess().getNameIDTerminalRuleCall_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getFragmentWithActionRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_2_0, 
        		"ID");
	    }

)
)(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getFragmentWithActionRule());
	        }
        }
	otherlv_3=RULE_ID
	{
		newLeafNode(otherlv_3, grammarAccess.getFragmentWithActionAccess().getRef2PRFNamedCrossReference_3_0()); 
	}

)
)?)
;





// Entry rule entryRuleFragmentWithAction2
entryRuleFragmentWithAction2 returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getFragmentWithAction2Rule()); }
	 iv_ruleFragmentWithAction2=ruleFragmentWithAction2 
	 { $current=$iv_ruleFragmentWithAction2.current; } 
	 EOF 
;

// Rule FragmentWithAction2
ruleFragmentWithAction2 returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((
    {
        $current = forceCreateModelElementAndSet(
            grammarAccess.getFragmentWithAction2Access().getPRFNamedWithActionPrevAction_0(),
            $current);
    }
)(
(
		lv_name_1_0=RULE_ID
		{
			newLeafNode(lv_name_1_0, grammarAccess.getFragmentWithAction2Access().getNameIDTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getFragmentWithAction2Rule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_1_0, 
        		"ID");
	    }

)
)(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getFragmentWithAction2Rule());
	        }
        }
	otherlv_2=RULE_ID
	{
		newLeafNode(otherlv_2, grammarAccess.getFragmentWithAction2Access().getRef2PRFNamedCrossReference_2_0()); 
	}

)
)?)
;





// Entry rule entryRuleFragmentWithAction3
entryRuleFragmentWithAction3 returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getFragmentWithAction3Rule()); }
	 iv_ruleFragmentWithAction3=ruleFragmentWithAction3 
	 { $current=$iv_ruleFragmentWithAction3.current; } 
	 EOF 
;

// Rule FragmentWithAction3
ruleFragmentWithAction3 returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((
(
		lv_name_0_0=RULE_ID
		{
			newLeafNode(lv_name_0_0, grammarAccess.getFragmentWithAction3Access().getNameIDTerminalRuleCall_0_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getFragmentWithAction3Rule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_0_0, 
        		"ID");
	    }

)
)((
    {
        $current = forceCreateModelElementAndSet(
            grammarAccess.getFragmentWithAction3Access().getPRFNamedWithActionPrevAction_1_0(),
            $current);
    }
)
	otherlv_2=HyphenMinusGreaterThanSign
    {
    	newLeafNode(otherlv_2, grammarAccess.getFragmentWithAction3Access().getHyphenMinusGreaterThanSignKeyword_1_1());
    }
(
(
		lv_name_3_0=RULE_ID
		{
			newLeafNode(lv_name_3_0, grammarAccess.getFragmentWithAction3Access().getNameIDTerminalRuleCall_1_2_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getFragmentWithAction3Rule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_3_0, 
        		"ID");
	    }

)
)(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getFragmentWithAction3Rule());
	        }
        }
	otherlv_4=RULE_ID
	{
		newLeafNode(otherlv_4, grammarAccess.getFragmentWithAction3Access().getRef2PRFNamedCrossReference_1_3_0()); 
	}

)
)?)*)
;





// Entry rule entryRulePRFNamedFragment
entryRulePRFNamedFragment returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getPRFNamedFragmentRule()); }
	 iv_rulePRFNamedFragment=rulePRFNamedFragment 
	 { $current=$iv_rulePRFNamedFragment.current; } 
	 EOF 
;

// Rule PRFNamedFragment
rulePRFNamedFragment returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
(
		lv_name_0_0=RULE_ID
		{
			newLeafNode(lv_name_0_0, grammarAccess.getPRFNamedFragmentAccess().getNameIDTerminalRuleCall_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedFragmentRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_0_0, 
        		"ID");
	    }

)
)
;





// Entry rule entryRulePRFNamedRef
entryRulePRFNamedRef returns [EObject current=null]
	:
	{ newCompositeNode(grammarAccess.getPRFNamedRefRule()); }
	 iv_rulePRFNamedRef=rulePRFNamedRef 
	 { $current=$iv_rulePRFNamedRef.current; } 
	 EOF 
;

// Rule PRFNamedRef
rulePRFNamedRef returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
(
		{
			if ($current==null) {
	            $current = createModelElement(grammarAccess.getPRFNamedRefRule());
	        }
        }
	otherlv_0=RULE_ID
	{
		newLeafNode(otherlv_0, grammarAccess.getPRFNamedRefAccess().getRefPRFNamedCrossReference_0()); 
	}

)
)
;





