/*******************************************************************************
 * Copyright (c) 2015 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
grammar org.eclipse.xtext.parser.fragments.FragmentTestLanguage with org.eclipse.xtext.common.Terminals

generate fragmentTestLanguage "http://www.eclipse.org/2015/tmf/xtext/fragments"
 
Fragments: {Fragments} 
  ( '#1' element=Named
  | '#2' element=Named '->' ref=[Named]
  | '#3' element=NamedRefFirst
  | '#4' element=NamedWithAction
  | '#5' element=NamedWithActionInFragment
  | '#6' element=NamedWithActionInFragment2
  | '#7' element=NamedWithActionInFragment3
  )
;

Named: NamedFragment (
	  ':' ref=[Named]
	| '-' NamedRef
	)?
;

NamedRefFirst returns Named:
	ref=[Named] '<-' NamedFragment
;

NamedWithAction returns Named:
	Named {NamedWithAction.prev=current} name=ID (ref=[Named] ref2=[Named])?
;

NamedWithActionInFragment returns Named:
	FragmentWithAction ('-' ref=[Named])?
;

NamedWithActionInFragment2 returns Named:
	name=ID FragmentWithAction2 ('-' ref=[Named])?
;

NamedWithActionInFragment3 returns Named:
	FragmentWithAction3 ('-' ref=[Named])?
;

fragment FragmentWithAction returns Named:
	name=ID {NamedWithAction.prev=current} name=ID (ref2=[Named])?
;

fragment FragmentWithAction2 returns Named:
	{NamedWithAction.prev=current} name=ID (ref2=[Named])?
;

fragment FragmentWithAction3 returns Named:
	name=ID ({NamedWithAction.prev=current} '->' name=ID (ref2=[Named])?)* 
;

fragment NamedFragment returns Named:
	name=ID
;

fragment NamedRef returns Named:
	ref=[Named]
;
